// Turns an AnalyzeResult into (1) a one-line "at a glance" verdict for the
// banner, and (2) a plain-text block formatted for pasting into a CRM/lead
// note. Kept as pure functions, separate from rendering, so both the banner
// and the copy button build from the exact same summary logic.

import type { AnalyzeResult } from "./api";

function serviceCount(result: AnalyzeResult): number {
  return result.pages.byType.service?.count ?? 0;
}

function blogCount(result: AnalyzeResult): number {
  return result.pages.byType.blog?.count ?? 0;
}

function providerPhrase(result: AnalyzeResult): string {
  const { count } = result.providers;
  if (count === "unknown") return "providers unknown";
  if (count === 0) return "no providers found";
  return `${count} provider${count === 1 ? "" : "s"}`;
}

function locationPhrase(result: AnalyzeResult): string {
  const { count } = result.locations;
  if (count === "unknown") return "locations unknown";
  if (count === 0) return "no locations found";
  return `${count} location${count === 1 ? "" : "s"}`;
}

function storePhrase(result: AnalyzeResult): string {
  const { store } = result;
  if (store.hasStore) return `store (${store.platform ?? "unknown platform"}, ${store.productCount} products)`;
  return "no active store";
}

function platformPhrase(result: AnalyzeResult): string {
  const { cms, builder } = result.platform;
  const parts = [cms.value, builder.value].filter(Boolean);
  return parts.length ? parts.join(" + ") : "platform unknown";
}

/** One line: "WordPress + Elementor · 36 services · 170 blog posts · 12 providers · 1 location · no active store" */
export function oneLineSummary(result: AnalyzeResult): string {
  const parts = [
    platformPhrase(result),
    `${serviceCount(result)} services`,
    `${blogCount(result)} blog posts`,
    providerPhrase(result),
    locationPhrase(result),
    storePhrase(result),
  ];
  return parts.join(" · ");
}

/** Plain-text block for pasting into a CRM / lead note. */
export function toClipboardText(result: AnalyzeResult): string {
  const { platform, pages, store, providers, locations, crawl } = result;
  const lines: string[] = [];

  lines.push(`Website Analysis: ${result.url}`);
  lines.push(oneLineSummary(result));
  lines.push("");

  lines.push(`Platform: ${platform.cms.value ?? "unknown"}${platform.builder.value ? ` + ${platform.builder.value}` : ""}`);
  lines.push(`E-commerce: ${platform.ecommerce.value ?? "none detected"}`);
  lines.push(
    `Store: ${store.hasStore ? `Yes — ${store.productCount} products, ${store.categoryCount} categories` : "No active store"}`
  );
  lines.push("");

  lines.push(`Pages: ${pages.total} total`);
  const byType = Object.entries(pages.byType).sort((a, b) => b[1].count - a[1].count);
  const { beforeAfterGallery } = result;
  for (const [type, bucket] of byType) {
    const baNote =
      type === "beforeAfter" && typeof beforeAfterGallery.caseCount === "number"
        ? ` (${beforeAfterGallery.caseCount} distinct cases, ${beforeAfterGallery.imageCount} images)`
        : "";
    lines.push(`  - ${type}: ${bucket.count}${baNote}`);
  }
  lines.push("");

  lines.push(`Providers: ${typeof providers.count === "number" ? providers.count : "unknown"}`);
  for (const p of providers.list) {
    const cred = p.credentials ? ` ${p.credentials}` : "";
    const role = p.role ? ` — ${p.role}` : "";
    lines.push(`  - ${p.name}${cred}${role}`);
  }
  lines.push("");

  lines.push(`Locations: ${typeof locations.count === "number" ? locations.count : "unknown"}`);
  for (const l of locations.list) {
    const bits = [l.name, l.address, l.phone].filter(Boolean).join(" — ");
    lines.push(`  - ${bits}`);
  }

  if (crawl.warnings.length) {
    lines.push("");
    lines.push("Warnings:");
    for (const w of crawl.warnings) lines.push(`  - ${w}`);
  }

  lines.push("");
  lines.push(`Generated by Website Analyzer · discovered via ${crawl.discoveredVia} · ${crawl.urlsSeen} URLs seen`);

  return lines.join("\n");
}
